title: "Yang Lab"
email: haofrankyang@jhu.edu
description: "Research at Johns Hopkins University"
url: "https://web-d6h.pages.dev"
baseurl: ""

remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-include-cache

# 禁用默认 sidebar
defaults:
  - scope:
      path: ""
    values:
      sidebar: false
